/*
 * This C++ source file was generated by the Gradle 'init' task.
 */
#ifndef SIMPLE_GRAPH_LIBRARY_H
#define SIMPLE_GRAPH_LIBRARY_H

#ifdef _WIN32
#define SIMPLE_GRAPH_LIBRARY_EXPORT_FUNC __declspec(dllexport)
#else
#define SIMPLE_GRAPH_LIBRARY_EXPORT_FUNC
#endif

#include <string>

namespace simple_graph_library {
    class Greeter {
        public:
        std::string SIMPLE_GRAPH_LIBRARY_EXPORT_FUNC greeting();
    };
}

#endif
