/*
 * This C++ source file was generated by the Gradle 'init' task.
 */

#include "simple_graph_library.h"
#include <cassert>

int main() {
    simple_graph_library::Greeter greeter;
    assert(greeter.greeting().compare("Hello, World!") == 0);
    return 0;
}
