/*
 * This C++ source file was generated by the Gradle 'init' task.
 */

#include <iostream>
#include <stdlib.h>
#include "simple_graph_library.h"

std::string simple_graph_library::Greeter::greeting() {
    return std::string("Hello, World!");
}
